CREATE TABLE HeartRate
(
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	PersonId UNIQUEIDENTIFIER NOT NULL,
	Reading INT NOT NULL,
	[Timestamp] DATETIME2 NOT NULL,

	ReadForIntegration BIT NOT NULL DEFAULT 0
);