version: "3.8"

services:
  connector-consumer:
    build:
      context: ./src/
      dockerfile: Connector.Consumer.Worker/Dockerfile
    container_name: connector-consumer
    environment:
      - InfluxDbConfig__Host=http://database_cloud:8086/
      - InfluxDbConfig__Token=o7X6Q48Y8TycSLHnAVUNmkvDtnngfOS0ZM01JjNUBaQhq-j2NSlDlaZm6FkCLSIzceBE90pRlCveagZ5uHZC-g==
      - RabbitMqConfig__Host=broker_mqtt
      - RabbitMqConfig__User=admin
      - RabbitMqConfig__Password=EQ3MrrGBwn8bAgaUz9Hjb3LuvP
    networks:
      - network_cloud
      - network_link_fog_cloud
    depends_on:
      - database_cloud
      - broker_mqtt

  connector-faker_dev:
    image: tcc/connector-faker
    build:
      context: ./src/Connector.Faker.Worker/
      dockerfile: Dockerfile
    container_name: connector-faker_dev
    environment:
      - ConnectionStrings__Default=Server=database_fog;Database=VitalSignReadings;User=sa;Password=4eFmpjPQLJK2NsoPrBQugHjo;TrustServerCertificate=True;
    networks:
      - network_fog
    depends_on:
      - database_fog

  connector-producer_dev:
    image: tcc/connector-producer
    build:
      context: ./src/
      dockerfile: Connector.Producer.Worker/Dockerfile
    container_name: connector-producer_dev
    environment:
      - ConnectionStrings__Default=Server=database_fog;Database=VitalSignReadings;User=sa;Password=4eFmpjPQLJK2NsoPrBQugHjo;TrustServerCertificate=True;
      - RabbitMqConfig__Host=broker_mqtt
      - RabbitMqConfig__User=admin
      - RabbitMqConfig__Password=EQ3MrrGBwn8bAgaUz9Hjb3LuvP
      - ConnectorConfig__FogNode__Id=40c35b8e-362f-4940-8eaf-b34621371b88
      - ConnectorConfig__FogNode__Name=Ed. Columbia
      - ConnectorConfig__FogNode__Latitude=-29.687997
      - ConnectorConfig__FogNode__Longitude=-51.129529
    networks:
      - network_fog
      - network_link_fog_cloud
    depends_on:
      - database_fog
      - broker_mqtt