version: "3.8"

services:
  broker_mqtt:
    image: rabbitmq:3.11.10-management-alpine
    container_name: broker_mqtt
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=EQ3MrrGBwn8bAgaUz9Hjb3LuvP    
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_volume:/var/lib/rabbitmq
    networks:
      - network_link_fog_cloud

  database_fog:
    user: root
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    container_name: database_fog
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=4eFmpjPQLJK2NsoPrBQugHjo
      - MSSQL_PID=Developer
    ports:
      - "54331:1433"
    volumes:
      - sqlserver_fog:/var/opt/mssql/data/
      - ./infra/sqlserver-fog/mssql.conf:/var/opt/mssql/mssql.conf
    networks:
      - network_fog

  dashboards_fog:
    image: grafana/grafana:9.4.3
    container_name: dashboards_fog
    ports:
      - "3001:3000"
    networks:
      - network_fog
    volumes:
      - grafana_fog_data:/var/lib/grafana
      - grafana_fog_home:/usr/share/grafana
      - grafana_fog_logs:/usr/share/grafana
      - grafana_fog_plugins:/var/lib/grafana/plugins
      - grafana_fog_provisioning:/etc/grafana/provisioning    

  influxdb:
    image: influxdb:2.6-alpine
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_ORG=MinhaHistoriaDigital
      - DOCKER_INFLUXDB_INIT_BUCKET=datalake_cloud
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=o7X6Q48Y8TycSLHnAVUNmkvDtnngfOS0ZM01JjNUBaQhq-j2NSlDlaZm6FkCLSIzceBE90pRlCveagZ5uHZC-g==
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=Pass123#
    volumes:
      # - ./infra/influxdb/config.yml:/etc/influxdb/config.yml:ro
      - influxdb_data:/var/lib/influxdb2
    networks:
      - network_cloud

  dashboards_cloud:
    user: root
    image: grafana/grafana:9.4.3
    container_name: dashboards_cloud
    ports:
      - "3002:3000"
    networks:
      - network_cloud
    volumes:
      - grafana_cloud_data:/var/lib/grafana
      - grafana_cloud_home:/usr/share/grafana
      - grafana_cloud_logs:/usr/share/grafana
      - grafana_cloud_plugins:/var/lib/grafana/plugins
      - grafana_cloud_provisioning:/etc/grafana/provisioning 

  # integrador-faker:
  #   build:
  #     context: ./src/Integrador.Faker.Worker/
  #     dockerfile: Dockerfile
  #   container_name: integrador-faker
  #   environment:
  #     - ConnectionStrings__Default=Server=database_fog;Database=VitalSignReadings;User=sa;Password=4eFmpjPQLJK2NsoPrBQugHjo;
  #   networks:
  #     - network_fog
  #   depends_on:
  #     - database_fog

volumes:
  rabbitmq_volume:
  sqlserver_fog:
  sqlserver_cloud:
  opentsdb_data:
  grafana_fog_data:
  grafana_fog_home:
  grafana_fog_logs:
  grafana_fog_plugins:
  grafana_fog_provisioning:
  influxdb_data:
  grafana_cloud_data:
  grafana_cloud_home:
  grafana_cloud_logs:
  grafana_cloud_plugins:
  grafana_cloud_provisioning:

networks:
  network_link_fog_cloud:
    driver: bridge
  network_fog:
    driver: bridge
  network_cloud:
    driver: bridge
  