CREATE TABLE HeartRate
(
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),	
	FogNodeId UNIQUEIDENTIFIER NOT NULL,
	PersonId UNIQUEIDENTIFIER NOT NULL,
	[Value] INT NOT NULL,
	[Timestamp] DATETIME2 NOT NULL,
);
